config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "homes#top"

   resources :users, only: [:index, :show, :edit, :update, :destroy]
   resources :posts, only: [:new, :index, :create, :show, :edit, :update, :destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  has_one_attached :image
  belongs_to :users
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    users_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
    @post = Post.new
  end

  def create
    post = Post.new(post_params)
    post.user_id = current_user.id
    post.save
    redirect_to posts_path
  end

  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    post = Post.find(params[:id])
    post.update(post_params)
    redirect_to post_path(post.id)
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to posts_path
  end

  private

  def post_params
    params.require(:post).permit(:title, :body)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    user = User.find(params[:id])
    user.update(user_params)
    redirect_to user_path(user.id)
  end

  def destroy
    user = User.find(params[:id])
    user.destroy
    redirect_to users_path
  end

  private

  def user_params
    params.require(:user).permit(:name)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homes/top.html.erb
<h1 class="text-center">ようこそ</h1>
  <div class="text-center pt-5">
    <%= link_to "ログイン", new_user_session_path, class: 'btn btn-info rounded-pill mx-3 my-1' %>
    <%= link_to "新規登録", new_user_registration_path, class: 'btn btn-info rounded-pill mx-3 my-1' %>
  </div>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="/about" style="font-family: cursive;">

    </a>
      <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
      </button>
        <div class="navbar-collapse collpse show" id="navbarNavDropdown" style>
          <ul class="navbar-nav ml-auto">


    <% if user_signed_in? %>
      <li class="nav-item"><%= link_to "マイページ", user_path(current_user.id), class: 'btn btn-outline-info rounded-pill mx-3 my-1' %></li>
      <li class="nav-item"><%= link_to "投稿", new_post_path, class: 'btn btn-outline-info rounded-pill mx-3 my-1' %></li>
      <li class="nav-item"><%= link_to "投稿一覧", posts_path, class: 'btn btn-outline-info rounded-pill mx-3 my-1' %></li>
    　<li class="nav-item"><%= link_to "ユーザー一覧", users_path, class: 'btn btn-outline-info rounded-pill mx-3 my-1' %></li>
      <li class="nav-item"><%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn btn-outline-info rounded-pill mx-3 my-1' %></li>
    <% else %>
      <li class="nav-item"><%= link_to "ログイン", new_user_session_path, class: 'btn btn-outline-info rounded-pill mx-3 my-1' %></li>
      <li class="nav-item"><%= link_to "新規登録", new_user_registration_path, class: 'btn btn-outline-info rounded-pill mx-3 my-1' %></li>
    <% end %>

        </ul>
      </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<h3>投稿編集画面</h3>
<%= form_with model: @post do |f| %>
  <h4>タイトル</h4>
    <%= f.text_field :title %>
    <%= f.text_field :body %>
    <%= f.submit '保存する', class: 'btn btn-info rounded-pill' %>
    <% end %>
    <%= link_to "詳細ページに戻る", post_path(@post.id), class: "btn btn-info rounded-pill" %>

app/views/posts/index.html.erb
<h3>投稿一覧</h3>
<table class="table table-striped">
  <thead>
    <tr>
      <th>タイトル</th>
      <th>投稿詳細文</th>
    </tr>
  </thead>
  <% @posts.each do |post| %>
  <tbody>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.body %></td>
        <td><%= link_to "詳細", post_path(post.id) %></td>
      </tr>
  </tbody>
  <% end %>
</table>

app/views/posts/new.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-8 offset-md-1 mt-5">
<h3>投稿</h3>
<%= form_with model: @post, url: posts_path, method: :post do |f| %>
  <h4>タイトル</h4>
  <%= f.text_field :title %>

  <h4>本文</h4>
  <%= f.text_area :body %>

  <%= f.submit '投稿' %>
<% end %>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-8 offset-md-1 mt-5">
      <table class="table">
        <thead>
          <tr>
            <th>タイトル</th>
            <th>本文</th>
            <th></th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><%= @post.title %></td>
            <td><%= @post.body %></td>
            <td><%= link_to "編集する", edit_post_path(@post.id), class: "btn btn-info rounded-pill" %></td>
            <td><%= link_to "削除する", post_path(@post.id), method: :delete, "data-confirm" => "本当に削除しますか?", class: "btn btn-info rounded-pill" %></td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-8 offset-md-1 mt-5">
      <h3>ユーザー編集画面</h3>
        <%= form_with model: @user do |f| %>
          <h4>名前</h4>
        <%= f.text_field :name %>
        <%= f.submit '保存する', class: 'btn btn-info rounded-pill' %>
        <% end %>
        <%= link_to "詳細ページに戻る", user_path(@user.id), class: "btn btn-info rounded-pill" %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th>ユーザーネーム</th>
    </tr>
  </thead>
  <% @users.each do |user| %>
  <tbody>
      <tr>
        <td><%= user.name %></td>
        <td><%= link_to "詳細ページ", user_path(user.id) %></td>
      </tr>
  </tbody>
  <% end %>
</table>

app/views/users/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-8 offset-md-1 mt-5">
      <table class="table">
        <thead>
          <tr>
            <th>ユーザーネーム</th>
            <th></th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><%= @user.name %></td>
            <td><%= link_to "編集する", edit_user_path(@user.id), class: "btn btn-info rounded-pill" %></td>
            <td><%= link_to "削除する", user_path(@user.id), method: :delete, "data-confirm" => "本当に削除しますか?", class: "btn btn-info rounded-pill" %></td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>